CREATE TABLE AULA_SEQUENCE (
ID NUMBER, DESCRICAO VARCHAR2 (40));

INSERT INTO AULA_SEQUENCE VALUES (1, 'TESTE');

CREATE SEQUENCE PRIMEIRA_SEQUENCIA;

SELECT PRIMEIRA_SEQUENCIA.NEXTVAL FROM DUAL;

INSERT INTO AULA_SEQUENCE VALUES (PRIMEIRA_SEQUENCIA.NEXTVAL, 'TESTE 2');

SELECT * FROM AULA_SEQUENCE ORDER BY 1;

CREATE SEQUENCE SEGUNDA_SEQUENCIA START WITH 10 INCREMENT BY 5;

CREATE SEQUENCE TERCEIRA_SEQUENCIA START WITH 10 INCREMENT BY 5 MAXVALUE 200 CYCLE;
