CREATE TABLE T_TESTE_SEQUENCE
(
    CD_TESTE_SQ NUMBER(3) NOT NULL,
    NH_TESTE_SQ VARCHAR2(30) NOT NULL
);

ALTER TABLE T_TESTE_SEQUENCE
ADD CONSTRAINT PK_T_TESTE_SEQUENCE
PRIMARY KEY (CD_TESTE_SQ);

CREATE SEQUENCE SQ_T_TESTE_SEQUENCE
START WITH 1 --PRIMEIRO N�MERO A SER GERADO
INCREMENT BY 1 --VALOR DO INCREMENTO (N�O PODE SER ZERO)
MAXVALUE 999 --MAIOR VALOR DA SEQUENCE 999
NOCACHE -- SEM CACHE 
NOCYCLE; --Nao REINICIA

INSERT INTO T_TESTE_SEQUENCE VALUES (SQ_T_TESTE_SEQUENCE.NEXTVAL, 'TESTE');
