CREATE SEQUENCE ORDER_ID_SEQ START WITH 100 INCREMENT BY 1;

CREATE TABLE ORDERS (
ORDER_ID NUMBER, CUSTOMER_NAME VARCHAR2(40), ORDER_DATE NUMBER);

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_NAME, ORDER_DATE) VALUES (ORDER_ID_SEQ.NEXTVAL,'PEDRO', '2');

ALTER SEQUENCE ORDER_ID_SEQ  START WITH 200;
